import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { requireCronAuth } from "@/lib/cron-auth";
import { generateMarketingPack, MARKETING_TOPICS } from "@/lib/marketing-engine";

/**
 * Weekly marketing autopilot (Mondays, after the digest).
 *
 * Drafts a three-channel pack on a rotating topic and stores it as DRAFT
 * SocialPost rows (autoGenerated=true), then notifies every admin. Nothing
 * is ever published without a human pressing the button — this replaces
 * the content-production half of a marketing team, not editorial judgement.
 */
export async function POST(req: NextRequest) {
  const auth = requireCronAuth(req.headers.get("authorization"));
  if (!auth.authorized) return auth.response ?? NextResponse.json({ error: "unauthorized" }, { status: 401 });

  try {
    // Rotate topics by ISO week so consecutive packs don't repeat.
    const rotation = ["aiact-deadline", "methodology", "leverage", "shadow-ai", "literacy"];
    const week = Math.floor(Date.now() / (7 * 86_400_000));
    const topic = rotation[week % rotation.length];

    const drafts = await generateMarketingPack(topic, ["linkedin", "twitter", "newsletter"]);

    await db.socialPost.createMany({
      data: drafts.map((d) => ({
        content: d.content,
        platform: d.platform,
        status: "draft",
        category: d.category,
        autoGenerated: true,
      })),
    });

    const admins = await db.user.findMany({ where: { role: "admin" }, select: { id: true } });
    if (admins.length > 0) {
      await db.notification.createMany({
        data: admins.map((a) => ({
          userId: a.id,
          type: "marketing_pack",
          title: "Weekly marketing pack drafted",
          message: `${drafts.length} drafts on "${MARKETING_TOPICS[topic]?.label ?? topic}" are waiting for review in Admin → Social.`,
        })),
      });
    }

    return NextResponse.json({ ok: true, topic, drafts: drafts.length });
  } catch (error) {
    console.error("[CRON_MARKETING_PACK]", error);
    return NextResponse.json({ error: "generation failed" }, { status: 500 });
  }
}
