/**
 * Static obligation catalogue for gap radar and coverage matrix.
 * Codes are stable E-ARI identifiers; labels summarize article headings (verify against Regulation (EU) 2024/1689 for your use case).
 */

export interface AiActObligation {
  code: string;
  label: string;
  severity: "critical" | "major" | "minor";
  recommendedArtifactType: string;
  ownerRoleHint?: string;
  hintArticles: string[];
}

export const AI_ACT_OBLIGATIONS: AiActObligation[] = [
  {
    code: "AI_ACT_ART_9",
    label: "Risk management system throughout the lifecycle",
    severity: "critical",
    recommendedArtifactType: "policy",
    ownerRoleHint: "CIO",
    hintArticles: ["Art.9", "Annex IV"],
  },
  {
    code: "AI_ACT_ART_10",
    label: "Data and data governance",
    severity: "critical",
    recommendedArtifactType: "dpia",
    ownerRoleHint: "DPO",
    hintArticles: ["Art.10", "Annex IV §3"],
  },
  {
    code: "AI_ACT_ART_11",
    label: "Technical documentation",
    severity: "critical",
    recommendedArtifactType: "model_card",
    ownerRoleHint: "Head of ML",
    hintArticles: ["Art.11", "Annex IV"],
  },
  {
    code: "AI_ACT_ART_12",
    label: "Record-keeping / logging",
    severity: "major",
    recommendedArtifactType: "policy",
    ownerRoleHint: "CISO",
    hintArticles: ["Art.12"],
  },
  {
    code: "AI_ACT_ART_13",
    label: "Transparency and provision of information to deployers (high-risk)",
    severity: "major",
    recommendedArtifactType: "instructions_for_use",
    ownerRoleHint: "Product",
    hintArticles: ["Art.13"],
  },
  {
    code: "AI_ACT_ART_14",
    label: "Human oversight",
    severity: "critical",
    recommendedArtifactType: "policy",
    ownerRoleHint: "Operations",
    hintArticles: ["Art.14"],
  },
  {
    code: "AI_ACT_ART_15",
    label: "Accuracy, robustness and cybersecurity",
    severity: "critical",
    recommendedArtifactType: "policy",
    ownerRoleHint: "CISO",
    hintArticles: ["Art.15"],
  },
  {
    code: "AI_ACT_ART_16",
    label: "Obligations of high-risk AI system operators (deployer core duties)",
    severity: "critical",
    recommendedArtifactType: "policy",
    ownerRoleHint: "AI owner",
    hintArticles: ["Art.16"],
  },
  {
    code: "AI_ACT_ART_17",
    label: "Quality management system",
    severity: "critical",
    recommendedArtifactType: "policy",
    ownerRoleHint: "Quality",
    hintArticles: ["Art.17"],
  },
  {
    code: "AI_ACT_ART_18",
    label: "Documentation for high-risk AI (operator-facing)",
    severity: "major",
    recommendedArtifactType: "technical_doc",
    ownerRoleHint: "Compliance",
    hintArticles: ["Art.18"],
  },
  {
    code: "AI_ACT_ART_19",
    label: "Automatically generated logs (deployer)",
    severity: "major",
    recommendedArtifactType: "policy",
    ownerRoleHint: "CISO",
    hintArticles: ["Art.19"],
  },
  {
    code: "AI_ACT_ART_20",
    label: "Corrective actions and duty of information",
    severity: "major",
    recommendedArtifactType: "incident_report",
    ownerRoleHint: "Compliance",
    hintArticles: ["Art.20"],
  },
  {
    code: "AI_ACT_ART_21",
    label: "Cooperation with competent authorities",
    severity: "minor",
    recommendedArtifactType: "minutes",
    ownerRoleHint: "Legal",
    hintArticles: ["Art.21"],
  },
  {
    code: "AI_ACT_ART_22",
    label: "Obligations of authorized representatives",
    severity: "major",
    recommendedArtifactType: "contract",
    ownerRoleHint: "Legal",
    hintArticles: ["Art.22"],
  },
  {
    code: "AI_ACT_ART_23",
    label: "Obligations of importers",
    severity: "major",
    recommendedArtifactType: "procurement",
    ownerRoleHint: "Procurement",
    hintArticles: ["Art.23"],
  },
  {
    code: "AI_ACT_ART_24",
    label: "Obligations of distributors",
    severity: "major",
    recommendedArtifactType: "contract",
    ownerRoleHint: "Channel",
    hintArticles: ["Art.24"],
  },
  {
    code: "AI_ACT_ART_25",
    label: "Responsibilities along the value chain",
    severity: "major",
    recommendedArtifactType: "contract",
    ownerRoleHint: "Legal",
    hintArticles: ["Art.25"],
  },
  {
    code: "AI_ACT_ART_26",
    label: "Obligations of deployers of high-risk AI systems",
    severity: "critical",
    recommendedArtifactType: "policy",
    ownerRoleHint: "Business owner",
    hintArticles: ["Art.26"],
  },
  {
    code: "AI_ACT_ART_27",
    label: "Fundamental rights impact assessment (FRIA) for deployers",
    severity: "critical",
    recommendedArtifactType: "dpia",
    ownerRoleHint: "DPO",
    hintArticles: ["Art.27"],
  },
  {
    code: "AI_ACT_ART_50",
    label: "Transparency obligations for certain AI systems",
    severity: "major",
    recommendedArtifactType: "policy",
    ownerRoleHint: "Product",
    hintArticles: ["Art.50"],
  },
  {
    code: "AI_ACT_ART_51",
    label: "Obligations for providers of general-purpose AI models",
    severity: "critical",
    recommendedArtifactType: "model_card",
    ownerRoleHint: "Head of ML",
    hintArticles: ["Art.51"],
  },
  {
    code: "AI_ACT_ART_52",
    label: "Authorised representative of general-purpose AI model provider (third country)",
    severity: "minor",
    recommendedArtifactType: "contract",
    ownerRoleHint: "Legal",
    hintArticles: ["Art.52"],
  },
  {
    code: "AI_ACT_ART_53",
    label: "Downstream obligations for integrators of general-purpose AI models",
    severity: "major",
    recommendedArtifactType: "contract",
    ownerRoleHint: "Product",
    hintArticles: ["Art.53"],
  },
  {
    code: "AI_ACT_ART_55",
    label: "EU database for high-risk AI systems (provider registration duties)",
    severity: "major",
    recommendedArtifactType: "technical_doc",
    ownerRoleHint: "Regulatory",
    hintArticles: ["Art.55"],
  },
  {
    code: "AI_ACT_ART_56",
    label: "Market surveillance coordination and pen tests (summary duty)",
    severity: "minor",
    recommendedArtifactType: "audit_report",
    ownerRoleHint: "Compliance",
    hintArticles: ["Art.56"],
  },
  {
    code: "AI_ACT_ART_71",
    label: "Post-market monitoring by providers (reporting & analysis)",
    severity: "critical",
    recommendedArtifactType: "minutes",
    ownerRoleHint: "Compliance",
    hintArticles: ["Art.71"],
  },
  {
    code: "AI_ACT_ART_72",
    label: "Post-market monitoring",
    severity: "major",
    recommendedArtifactType: "minutes",
    ownerRoleHint: "Compliance",
    hintArticles: ["Art.72"],
  },
  {
    code: "AI_ACT_ART_73",
    label: "Serious incident reporting",
    severity: "critical",
    recommendedArtifactType: "incident_report",
    ownerRoleHint: "CISO",
    hintArticles: ["Art.73"],
  },
  {
    code: "AI_ACT_ANNEX_III_1",
    label: "Annex III area: biometrics",
    severity: "critical",
    recommendedArtifactType: "dpia",
    ownerRoleHint: "DPO",
    hintArticles: ["Annex III"],
  },
  {
    code: "AI_ACT_ANNEX_III_2",
    label: "Annex III area: critical infrastructure",
    severity: "critical",
    recommendedArtifactType: "policy",
    ownerRoleHint: "CISO",
    hintArticles: ["Annex III"],
  },
  {
    code: "AI_ACT_ANNEX_III_3",
    label: "Annex III area: education & vocational training",
    severity: "major",
    recommendedArtifactType: "policy",
    ownerRoleHint: "Compliance",
    hintArticles: ["Annex III"],
  },
  {
    code: "AI_ACT_ANNEX_III_4",
    label: "Annex III area: employment & worker management",
    severity: "critical",
    recommendedArtifactType: "dpia",
    ownerRoleHint: "HR Legal",
    hintArticles: ["Annex III"],
  },
  {
    code: "AI_ACT_ANNEX_III_5",
    label: "Annex III area: access to essential services (private & public)",
    severity: "critical",
    recommendedArtifactType: "dpia",
    ownerRoleHint: "Compliance",
    hintArticles: ["Annex III"],
  },
  {
    code: "AI_ACT_ANNEX_III_6",
    label: "Annex III area: law enforcement",
    severity: "critical",
    recommendedArtifactType: "policy",
    ownerRoleHint: "Legal",
    hintArticles: ["Annex III"],
  },
  {
    code: "AI_ACT_ANNEX_III_7",
    label: "Annex III area: migration & border control",
    severity: "critical",
    recommendedArtifactType: "policy",
    ownerRoleHint: "Legal",
    hintArticles: ["Annex III"],
  },
  {
    code: "AI_ACT_ANNEX_III_8",
    label: "Annex III area: justice & democratic processes",
    severity: "critical",
    recommendedArtifactType: "policy",
    ownerRoleHint: "Legal",
    hintArticles: ["Annex III"],
  },
  {
    code: "AI_ACT_ART_5_1_a",
    label: "Prohibited: subliminal / manipulative techniques (material harm)",
    severity: "critical",
    recommendedArtifactType: "policy",
    ownerRoleHint: "Legal",
    hintArticles: ["Art.5(1)(a)"],
  },
  {
    code: "AI_ACT_ART_5_1_b",
    label: "Prohibited: exploitation of vulnerabilities",
    severity: "critical",
    recommendedArtifactType: "policy",
    ownerRoleHint: "Legal",
    hintArticles: ["Art.5(1)(b)"],
  },
  {
    code: "AI_ACT_ART_5_1_c",
    label: "Prohibited: social scoring by public authorities",
    severity: "critical",
    recommendedArtifactType: "policy",
    ownerRoleHint: "Legal",
    hintArticles: ["Art.5(1)(c)"],
  },
  {
    code: "AI_ACT_ART_5_1_d",
    label: "Prohibited: real-time remote biometric ID in publicly accessible spaces (exceptions regime)",
    severity: "critical",
    recommendedArtifactType: "policy",
    ownerRoleHint: "Legal",
    hintArticles: ["Art.5(1)(d)"],
  },
  {
    code: "AI_ACT_ART_28",
    label: "Monitoring high-risk AI systems operated by deployers",
    severity: "major",
    recommendedArtifactType: "minutes",
    ownerRoleHint: "Operations",
    hintArticles: ["Art.28"],
  },
  {
    code: "AI_ACT_ART_29",
    label: "Reporting serious incidents by deployers",
    severity: "critical",
    recommendedArtifactType: "incident_report",
    ownerRoleHint: "CISO",
    hintArticles: ["Art.29"],
  },
  {
    code: "AI_ACT_ART_30",
    label: "EU database registration — deployer duties where applicable",
    severity: "major",
    recommendedArtifactType: "technical_doc",
    ownerRoleHint: "Regulatory",
    hintArticles: ["Art.30"],
  },
  {
    code: "AI_ACT_ART_47",
    label: "Conformity assessment — notified body involvement (high-risk)",
    severity: "major",
    recommendedArtifactType: "audit_report",
    ownerRoleHint: "Quality",
    hintArticles: ["Art.47"],
  },
  {
    code: "AI_ACT_ART_54",
    label: "EU declaration of conformity",
    severity: "major",
    recommendedArtifactType: "technical_doc",
    ownerRoleHint: "Compliance",
    hintArticles: ["Art.54"],
  },
  {
    code: "AI_ACT_ART_61",
    label: "Procedure for addressing national compliance concerns",
    severity: "minor",
    recommendedArtifactType: "minutes",
    ownerRoleHint: "Legal",
    hintArticles: ["Art.61"],
  },
  {
    code: "AI_ACT_ART_62",
    label: "Union safeguard procedure",
    severity: "minor",
    recommendedArtifactType: "minutes",
    ownerRoleHint: "Legal",
    hintArticles: ["Art.62"],
  },
  {
    code: "AI_ACT_ART_63",
    label: "Right to lodge complaint",
    severity: "minor",
    recommendedArtifactType: "policy",
    ownerRoleHint: "Legal",
    hintArticles: ["Art.63"],
  },
  {
    code: "AI_ACT_ART_64",
    label: "Investigations on systemic risks at EU level (GPAI)",
    severity: "major",
    recommendedArtifactType: "minutes",
    ownerRoleHint: "Compliance",
    hintArticles: ["Art.64"],
  },
  {
    code: "AI_ACT_ART_65",
    label: "Procedure for systemic risks & codes of practice",
    severity: "major",
    recommendedArtifactType: "policy",
    ownerRoleHint: "Compliance",
    hintArticles: ["Art.65"],
  },
  {
    code: "AI_ACT_ANNEX_IV_1",
    label: "Annex IV §1 General description of the AI system",
    severity: "major",
    recommendedArtifactType: "technical_doc",
    ownerRoleHint: "Head of ML",
    hintArticles: ["Annex IV §1"],
  },
  {
    code: "AI_ACT_ANNEX_IV_2",
    label: "Annex IV §2 System architecture / logical interactions",
    severity: "major",
    recommendedArtifactType: "technical_doc",
    ownerRoleHint: "Engineering",
    hintArticles: ["Annex IV §2"],
  },
  {
    code: "AI_ACT_ANNEX_IV_3",
    label: "Annex IV §3 Training data / methodology",
    severity: "critical",
    recommendedArtifactType: "dpia",
    ownerRoleHint: "DPO",
    hintArticles: ["Annex IV §3"],
  },
  {
    code: "AI_ACT_ANNEX_IV_4",
    label: "Annex IV §4 Performance metrics / robustness",
    severity: "major",
    recommendedArtifactType: "model_card",
    ownerRoleHint: "ML Lead",
    hintArticles: ["Annex IV §4"],
  },
  {
    code: "AI_ACT_ANNEX_IV_5",
    label: "Annex IV §5 Risk management measures",
    severity: "critical",
    recommendedArtifactType: "policy",
    ownerRoleHint: "Risk",
    hintArticles: ["Annex IV §5"],
  },
  {
    code: "AI_ACT_ANNEX_IV_6",
    label: "Annex IV §6 Lifecycle changes / versions",
    severity: "major",
    recommendedArtifactType: "technical_doc",
    ownerRoleHint: "Engineering",
    hintArticles: ["Annex IV §6"],
  },
  {
    code: "AI_ACT_ANNEX_IV_7",
    label: "Annex IV §7 Standards / specifications applied",
    severity: "minor",
    recommendedArtifactType: "audit_report",
    ownerRoleHint: "Quality",
    hintArticles: ["Annex IV §7"],
  },
  {
    code: "AI_ACT_ANNEX_IV_8",
    label: "Annex IV §8 Cybersecurity measures",
    severity: "critical",
    recommendedArtifactType: "policy",
    ownerRoleHint: "CISO",
    hintArticles: ["Annex IV §8"],
  },
  {
    code: "AI_ACT_ANNEX_IV_9",
    label: "Annex IV §9 Operational design domain / context of use",
    severity: "major",
    recommendedArtifactType: "technical_doc",
    ownerRoleHint: "Product",
    hintArticles: ["Annex IV §9"],
  },
];
