/**
 * Lightweight DOCX exports for compliance artifacts (FRIA / Annex IV summary).
 * Uses the same docx conventions as report-generator.ts (light theme).
 */

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  Footer,
  PageNumber,
} from "docx";

const FONT_HEADING = "Space Grotesk";
const FONT_BODY = "Inter";

function heading(text: string, level: typeof HeadingLevel[keyof typeof HeadingLevel]): Paragraph {
  return new Paragraph({
    heading: level,
    spacing: { before: 240, after: 120 },
    children: [new TextRun({ text, font: FONT_HEADING, bold: true, color: "1A1A2E", size: level === HeadingLevel.HEADING_1 ? 36 : 28 })],
  });
}

function body(text: string): Paragraph {
  return new Paragraph({
    spacing: { after: 120 },
    children: [new TextRun({ text, font: FONT_BODY, color: "2D3748", size: 22 })],
  });
}

function jsonBlock(label: string, data: unknown): Paragraph[] {
  const lines = [`${label}:`, JSON.stringify(data, null, 2)].join("\n");
  return [
    new Paragraph({
      spacing: { before: 120, after: 120 },
      children: [new TextRun({ text: lines, font: "Courier New", color: "334155", size: 18 })],
    }),
  ];
}

export async function buildFriaDocxBuffer(params: {
  systemName: string;
  fria: {
    affectedGroups: unknown;
    rightsAtRisk: unknown;
    mitigations: unknown;
    residualRisk: string | null;
    oversightDesign: string | null;
    status: string;
  };
}): Promise<Buffer> {
  const children: Paragraph[] = [
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
      children: [
        new TextRun({
          text: "Fundamental Rights Impact Assessment (FRIA) — Draft",
          font: FONT_HEADING,
          bold: true,
          size: 40,
          color: "1E40AF",
        }),
      ],
    }),
    body(`System: ${params.systemName}`),
    heading("Document status", HeadingLevel.HEADING_2),
    body(`Status: ${params.fria.status}`),
    heading("Affected groups", HeadingLevel.HEADING_2),
    ...jsonBlock("JSON", params.fria.affectedGroups),
    heading("Rights at risk", HeadingLevel.HEADING_2),
    ...jsonBlock("JSON", params.fria.rightsAtRisk),
    heading("Mitigations", HeadingLevel.HEADING_2),
    ...jsonBlock("JSON", params.fria.mitigations),
    heading("Residual risk", HeadingLevel.HEADING_2),
    body(params.fria.residualRisk || "(not specified)"),
    heading("Oversight design", HeadingLevel.HEADING_2),
    body(params.fria.oversightDesign || "(not specified)"),
    new Paragraph({
      spacing: { before: 400 },
      children: [
        new TextRun({
          text: "Generated by E-ARI Compliance — AI-assisted draft for internal review only.",
          italics: true,
          color: "64748B",
          size: 18,
          font: FONT_BODY,
        }),
      ],
    }),
  ];

  const doc = new Document({
    sections: [
      {
        properties: {},
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({ text: "Page ", font: FONT_BODY, size: 18 }),
                  new TextRun({ children: [PageNumber.CURRENT], font: FONT_BODY, size: 18 }),
                ],
              }),
            ],
          }),
        },
        children,
      },
    ],
  });

  return Buffer.from(await Packer.toBuffer(doc));
}

export async function buildTechnicalFileSummaryDocxBuffer(params: {
  systemName: string;
  technical: Record<string, unknown>;
}): Promise<Buffer> {
  const children: Paragraph[] = [
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
      children: [
        new TextRun({
          text: "Annex IV Technical Documentation — Summary Export",
          font: FONT_HEADING,
          bold: true,
          size: 36,
          color: "1E40AF",
        }),
      ],
    }),
    body(`System: ${params.systemName}`),
    heading("Sections (JSON)", HeadingLevel.HEADING_2),
    ...jsonBlock("technicalFile", params.technical),
  ];

  const doc = new Document({
    sections: [
      {
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [new TextRun({ children: [PageNumber.CURRENT], font: FONT_BODY, size: 18 })],
              }),
            ],
          }),
        },
        children,
      },
    ],
  });

  return Buffer.from(await Packer.toBuffer(doc));
}
