import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { db } from "@/lib/db";

export async function GET(req: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id || session.user.role !== "admin") {
      return Response.json({ error: "Unauthorized" }, { status: 403 });
    }

    const { searchParams } = new URL(req.url);
    const status = searchParams.get("status");
    const platform = searchParams.get("platform");

    const where: Record<string, unknown> = {};
    if (status && status !== "all") where.status = status;
    if (platform && platform !== "all") where.platform = platform;

    const posts = await db.socialPost.findMany({
      where,
      orderBy: { createdAt: "desc" },
    });

    return Response.json(posts);
  } catch (error) {
    console.error("[SOCIAL_POSTS_GET]", error);
    return Response.json({ error: "Failed to fetch social posts" }, { status: 500 });
  }
}

export async function POST(req: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id || session.user.role !== "admin") {
      return Response.json({ error: "Unauthorized" }, { status: 403 });
    }

    const body = await req.json();
    const { content, platform, mediaUrls, status, scheduledAt, category, autoGenerated, sourceData } = body;

    if (!content || !platform) {
      return Response.json({ error: "Content and platform are required" }, { status: 400 });
    }

    const validStatuses = ["draft", "scheduled", "publishing", "published", "failed"];
    const postStatus = validStatuses.includes(status) ? status : "draft";

    const post = await db.socialPost.create({
      data: {
        content,
        platform,
        mediaUrls: mediaUrls || null,
        status: postStatus,
        scheduledAt: scheduledAt ? new Date(scheduledAt) : null,
        category: category || null,
        autoGenerated: autoGenerated || false,
        sourceData: sourceData || null,
        createdBy: session.user.id,
      },
    });

    return Response.json(post, { status: 201 });
  } catch (error) {
    console.error("[SOCIAL_POSTS_POST]", error);
    return Response.json({ error: "Failed to create social post" }, { status: 500 });
  }
}
