'use client';

/**
 * Landing "magic" — living elements that extend the hero's motion language
 * across the rest of the page, so no section reads as a static slide.
 *
 * Everything here is deterministic framer-motion + rAF, GPU-cheap, and
 * respects prefers-reduced-motion (falls back to the finished frame).
 */

import { useEffect, useRef, useState } from 'react';
import { motion, useReducedMotion, useInView } from 'framer-motion';

// ─── Streaming insight card ──────────────────────────────────────────────────
// The Insight agent writing a narrative live, the way it does in the product.
// Types on scroll into view; segments carry inline score chips.

type Segment = { t: string } | { chip: string; tone: 'blue' | 'amber' };

const INSIGHT_SEGMENTS: Segment[] = [
  { t: 'Your organization demonstrates strong governance foundations' },
  { chip: '78/100', tone: 'blue' },
  { t: ' but faces a critical talent gap' },
  { chip: '44/100', tone: 'amber' },
  { t: ' that constrains AI execution capacity. Policies and frameworks are in place; the human capital to operationalize them is not.' },
];

const FULL_TEXT = INSIGHT_SEGMENTS.map((s) => ('t' in s ? s.t : ` ${s.chip} `)).join('');

export function InsightStream() {
  const prefersReducedMotion = useReducedMotion();
  const ref = useRef<HTMLDivElement>(null);
  const inView = useInView(ref, { once: true, margin: '-80px' });
  const [count, setCount] = useState(0);
  const done = count >= FULL_TEXT.length;

  useEffect(() => {
    if (prefersReducedMotion) { setCount(FULL_TEXT.length); return; }
    if (!inView) return;
    let i = 0;
    const iv = setInterval(() => {
      i += 2;
      setCount(i);
      if (i >= FULL_TEXT.length) clearInterval(iv);
    }, 18);
    return () => clearInterval(iv);
  }, [inView, prefersReducedMotion]);

  // Walk the segments, revealing up to `count` characters.
  let cursor = 0;
  const rendered: React.ReactNode[] = [];
  for (let s = 0; s < INSIGHT_SEGMENTS.length; s++) {
    const seg = INSIGHT_SEGMENTS[s];
    const raw = 't' in seg ? seg.t : ` ${seg.chip} `;
    const remaining = Math.max(0, count - cursor);
    if (remaining <= 0) break;
    const shown = raw.slice(0, remaining);
    if ('t' in seg) {
      rendered.push(<span key={s}>{shown}</span>);
    } else {
      rendered.push(
        <span
          key={s}
          className={`font-mono tabular-nums ${seg.tone === 'blue' ? 'text-eari-blue-light' : 'text-amber-300/90'}`}
        >
          {shown}
        </span>,
      );
    }
    cursor += raw.length;
  }

  return (
    <div ref={ref} className="rounded-xl border border-white/[0.06] bg-[#0e131c] p-7 h-full shadow-[0_20px_50px_-25px_rgba(0,0,0,0.6)]">
      <div className="flex items-center justify-between mb-5">
        <span className="font-mono text-[10px] uppercase tracking-[0.18em] text-slate-500">Insight agent · live</span>
        <span className="inline-flex items-center gap-1.5 rounded-md border border-white/[0.06] bg-white/[0.02] px-2 py-1 font-mono text-[10px] text-slate-400 tracking-[0.12em] uppercase">
          <span className={`h-1.5 w-1.5 rounded-full ${done ? 'bg-emerald-400' : 'bg-sky-400 animate-pulse'}`} />
          {done ? 'Generated' : 'Writing'}
        </span>
      </div>
      <div className="border-l-2 border-eari-blue/45 pl-5 min-h-[132px]">
        <p className="text-slate-100 font-sans leading-[1.65] text-[15px]">
          {rendered}
          {!done && !prefersReducedMotion && (
            <span className="inline-block w-[7px] h-[15px] translate-y-[2px] bg-sky-300/80 ml-px animate-pulse" />
          )}
        </p>
        {done && (
          <motion.p
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4 }}
            className="mt-4 text-slate-100 font-sans leading-[1.65] text-[15px]"
          >
            <span className="font-heading font-semibold text-slate-50">Recommended priority &mdash;</span>{' '}
            Invest in upskilling and AI career frameworks before scaling deployments.
          </motion.p>
        )}
      </div>
      <p className="mt-5 pt-4 border-t border-white/[0.05] text-[11px] font-mono text-slate-500 tracking-[0.04em]">
        Generated by AI &middot; grounded in your scores &middot; never alters calculated results
      </p>
    </div>
  );
}

// ─── Radar sweep ─────────────────────────────────────────────────────────────
// A slow rotating conic beam dropped into the methodology radar SVG so it
// reads as a live instrument rather than a frozen chart. Renders in SVG
// user units centered at (110,110); pass into the existing <svg viewBox>.

export function RadarSweep() {
  const prefersReducedMotion = useReducedMotion();
  if (prefersReducedMotion) return null;
  return (
    <>
      <defs>
        <linearGradient id="radarSweepGrad" x1="0%" y1="0%" x2="100%" y2="0%">
          <stop offset="0%" stopColor="rgba(56,189,248,0)" />
          <stop offset="100%" stopColor="rgba(56,189,248,0.28)" />
        </linearGradient>
      </defs>
      <motion.g
        style={{ transformOrigin: '110px 110px' }}
        animate={{ rotate: 360 }}
        transition={{ duration: 8, repeat: Infinity, ease: 'linear' }}
      >
        {/* Wedge from center — leading edge bright, trailing fades */}
        <path d="M110,110 L110,30 A80,80 0 0,1 180,68 Z" fill="url(#radarSweepGrad)" opacity="0.5" />
        <line x1="110" y1="110" x2="110" y2="30" stroke="rgba(56,189,248,0.55)" strokeWidth="0.8" />
      </motion.g>
    </>
  );
}

// ─── Pulsing radar data point ────────────────────────────────────────────────
// A soft expanding halo behind each data vertex. SVG-native, center given.

export function RadarPulse({ cx, cy, color, delay = 0 }: { cx: number; cy: number; color: string; delay?: number }) {
  const prefersReducedMotion = useReducedMotion();
  if (prefersReducedMotion) return null;
  return (
    <motion.circle
      cx={cx} cy={cy} r="2.5" fill={color}
      initial={{ opacity: 0.5, scale: 1 }}
      animate={{ opacity: [0.5, 0, 0.5], scale: [1, 3, 1] }}
      transition={{ duration: 3, repeat: Infinity, delay, ease: 'easeOut' }}
      style={{ transformOrigin: `${cx}px ${cy}px` }}
    />
  );
}

// ─── Animated CTA aura ───────────────────────────────────────────────────────
// Drifting conic glow behind the final CTA so the closer feels alive.

export function CtaAura() {
  const prefersReducedMotion = useReducedMotion();
  return (
    <div className="absolute inset-0 overflow-hidden pointer-events-none" aria-hidden="true">
      <motion.div
        className="absolute left-1/2 top-1/2 h-[520px] w-[820px] -translate-x-1/2 -translate-y-1/2 rounded-[40%] opacity-[0.18]"
        style={{ background: 'conic-gradient(from 0deg, #2563eb, #7c3aed, #0891b2, #2563eb)' }}
        animate={prefersReducedMotion ? undefined : { rotate: 360 }}
        transition={{ duration: 40, repeat: Infinity, ease: 'linear' }}
      />
      <div className="absolute inset-0 backdrop-blur-[100px]" />
      <div className="absolute inset-0 bg-navy-900/40" />
    </div>
  );
}

// ─── Reveal-on-scroll number ─────────────────────────────────────────────────
// Counts up when scrolled into view (for stat strips beyond the hero).

export function CountUpOnView({ to, suffix = '', className }: { to: number; suffix?: string; className?: string }) {
  const prefersReducedMotion = useReducedMotion();
  const ref = useRef<HTMLSpanElement>(null);
  const inView = useInView(ref, { once: true, margin: '-40px' });
  const [value, setValue] = useState(0);
  useEffect(() => {
    if (prefersReducedMotion) { setValue(to); return; }
    if (!inView) return;
    let raf = 0;
    const t0 = performance.now();
    const tick = (t: number) => {
      const p = Math.min(1, (t - t0) / 1300);
      setValue(Math.round(to * (1 - Math.pow(1 - p, 3))));
      if (p < 1) raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [inView, to, prefersReducedMotion]);
  return <span ref={ref} className={className}>{value}{suffix}</span>;
}
