"use client";

import { useEffect, useState, useCallback } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import { format, startOfMonth, endOfMonth, eachDayOfInterval, isSameMonth, isSameDay, isToday, addMonths, subMonths, startOfWeek, endOfWeek } from "date-fns";
import { toast } from "sonner";
import {
  ArrowLeft,
  Share2,
  Loader2,
  AlertTriangle,
  Plus,
  Send,
  Clock,
  FileEdit,
  Trash2,
  Calendar as CalendarIcon,
  PenLine,
  Users,
  BarChart3,
  ImagePlus,
  Sparkles,
  ExternalLink,
  Linkedin,
  Twitter,
  Facebook,
  CheckCircle2,
  XCircle,
  RefreshCw,
  Unplug,
  ChevronLeft,
  ChevronRight,
} from "lucide-react";
import { Navigation } from "@/components/shared/navigation";
import { Footer } from "@/components/shared/footer";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

// ─── Types ──────────────────────────────────────────────────────────────

interface SocialAccount {
  id: string;
  provider: string;
  accountName: string;
  accountHandle: string | null;
  accessToken: string | null;
  refreshToken: string | null;
  tokenExpiresAt: string | null;
  avatarUrl: string | null;
  isActive: boolean;
  lastSyncAt: string | null;
  createdAt: string;
  updatedAt: string;
}

interface SocialPost {
  id: string;
  content: string;
  platform: string;
  mediaUrls: string | null;
  status: string;
  scheduledAt: string | null;
  publishedAt: string | null;
  failedReason: string | null;
  category: string | null;
  autoGenerated: boolean;
  engagementMetrics: string | null;
  sourceData: string | null;
  createdBy: string | null;
  createdAt: string;
  updatedAt: string;
}

type SocialTab = "compose" | "calendar" | "accounts" | "analytics";

// ─── Platform Config ────────────────────────────────────────────────────

const PLATFORM_CONFIG: Record<string, { name: string; color: string; icon: React.ElementType; maxChars: number }> = {
  linkedin: { name: "LinkedIn", color: "#0A66C2", icon: Linkedin, maxChars: 3000 },
  twitter: { name: "Twitter/X", color: "#000000", icon: Twitter, maxChars: 280 },
  facebook: { name: "Facebook", color: "#1877F2", icon: Facebook, maxChars: 500 },
  all: { name: "All Platforms", color: "#10b981", icon: Share2, maxChars: 280 },
};

// ─── Helpers ────────────────────────────────────────────────────────────

function postStatusBadge(status: string) {
  switch (status) {
    case "draft":
      return <Badge className="bg-navy-700 text-muted-foreground border-border/50 text-xs"><FileEdit className="h-3 w-3 mr-1" />Draft</Badge>;
    case "scheduled":
      return <Badge className="bg-amber-500/15 text-amber-400 border-amber-500/30 text-xs"><Clock className="h-3 w-3 mr-1" />Scheduled</Badge>;
    case "published":
      return <Badge className="bg-emerald-500/15 text-emerald-400 border-emerald-500/30 text-xs"><CheckCircle2 className="h-3 w-3 mr-1" />Published</Badge>;
    case "failed":
      return <Badge className="bg-red-500/15 text-red-400 border-red-500/30 text-xs"><XCircle className="h-3 w-3 mr-1" />Failed</Badge>;
    case "publishing":
      return <Badge className="bg-eari-blue/15 text-eari-blue-light border-eari-blue/30 text-xs"><Loader2 className="h-3 w-3 mr-1 animate-spin" />Publishing</Badge>;
    default:
      return <Badge variant="secondary" className="text-xs">{status}</Badge>;
  }
}

function PlatformIcon({ platform, size = 16 }: { platform: string; size?: number }) {
  const config = PLATFORM_CONFIG[platform];
  if (!config) return <Share2 className="h-4 w-4" />;
  const Icon = config.icon;
  return <Icon style={{ width: size, height: size, color: config.color }} />;
}

function formatDate(dateStr: string) {
  return new Date(dateStr).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

// ─── Main Component ─────────────────────────────────────────────────────

export default function SocialMediaPage() {
  const { data: session, status } = useSession();
  const router = useRouter();

  const [activeTab, setActiveTab] = useState<SocialTab>("compose");
  const [posts, setPosts] = useState<SocialPost[]>([]);
  const [accounts, setAccounts] = useState<SocialAccount[]>([]);
  const [loading, setLoading] = useState(true);

  // Compose state
  const [composeContent, setComposeContent] = useState("");
  const [composePlatform, setComposePlatform] = useState("linkedin");
  const [composeCategory, setComposeCategory] = useState("custom");
  const [composeScheduledAt, setComposeScheduledAt] = useState("");
  const [composeMedia, setComposeMedia] = useState<string[]>([]);
  const [generating, setGenerating] = useState(false);
  const [publishingId, setPublishingId] = useState<string | null>(null);

  // Calendar state
  const [calendarMonth, setCalendarMonth] = useState(new Date());
  const [selectedDay, setSelectedDay] = useState<Date | null>(null);

  // Account dialog state
  const [showAccountDialog, setShowAccountDialog] = useState(false);
  const [accountForm, setAccountForm] = useState({
    provider: "linkedin",
    accountName: "",
    accountHandle: "",
    accessToken: "",
  });
  const [savingAccount, setSavingAccount] = useState(false);

  // Post detail dialog
  const [selectedPost, setSelectedPost] = useState<SocialPost | null>(null);

  // ─── Fetch Data ─────────────────────────────────────────────────────

  const fetchPosts = useCallback(async () => {
    try {
      const res = await fetch("/api/admin/social/posts");
      if (res.ok) {
        const data = await res.json();
        setPosts(data);
      }
    } catch {
      // silently fail
    }
  }, []);

  const fetchAccounts = useCallback(async () => {
    try {
      const res = await fetch("/api/admin/social/accounts");
      if (res.ok) {
        const data = await res.json();
        setAccounts(data);
      }
    } catch {
      // silently fail
    }
  }, []);

  useEffect(() => {
    if (status === "loading") return;
    if (!session || session.user?.role !== "admin") return;

    setLoading(true);
    Promise.all([fetchPosts(), fetchAccounts()]).finally(() => setLoading(false));
  }, [session, status, fetchPosts, fetchAccounts]);

  // ─── Access Control ─────────────────────────────────────────────────

  if (status === "loading") {
    return (
      <div className="min-h-screen flex flex-col bg-navy-900">
        <Navigation />
        <main className="flex-1 flex items-center justify-center">
          <div className="flex flex-col items-center gap-4">
            <Loader2 className="h-10 w-10 animate-spin text-eari-blue" />
            <p className="text-muted-foreground font-sans text-sm">Verifying access...</p>
          </div>
        </main>
      </div>
    );
  }

  if (!session || session.user?.role !== "admin") {
    return (
      <div className="min-h-screen flex flex-col bg-navy-900">
        <Navigation />
        <main className="flex-1 flex items-center justify-center px-4">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="glass-card rounded-2xl p-8 max-w-md w-full text-center"
          >
            <div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-destructive/10">
              <AlertTriangle className="h-8 w-8 text-destructive" />
            </div>
            <h2 className="font-heading text-xl font-semibold text-foreground mb-2">Access Denied</h2>
            <p className="text-muted-foreground font-sans text-sm mb-6">
              You do not have admin privileges to view this page.
            </p>
            <Button onClick={() => router.push("/admin")} className="bg-eari-blue hover:bg-eari-blue-dark text-white font-sans">
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to Admin
            </Button>
          </motion.div>
        </main>
        <Footer />
      </div>
    );
  }

  // ─── Handlers ──────────────────────────────────────────────────────

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      const res = await fetch("/api/admin/social/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ type: composeCategory === "custom" ? "promotion" : composeCategory }),
      });
      if (res.ok) {
        const data = await res.json();
        setComposeContent(data.content);
        if (data.platform && data.platform !== composePlatform) {
          setComposePlatform(data.platform);
        }
        if (data.category && data.category !== "custom") {
          setComposeCategory(data.category);
        }
        toast.success("Content generated successfully!");
      } else {
        toast.error("Failed to generate content");
      }
    } catch {
      toast.error("Failed to generate content");
    } finally {
      setGenerating(false);
    }
  };

  const handleSavePost = async (postStatus: string) => {
    if (!composeContent.trim()) {
      toast.error("Please enter post content");
      return;
    }

    try {
      const res = await fetch("/api/admin/social/posts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          content: composeContent,
          platform: composePlatform,
          status: postStatus,
          scheduledAt: postStatus === "scheduled" ? composeScheduledAt : undefined,
          category: composeCategory,
          mediaUrls: composeMedia.length > 0 ? JSON.stringify(composeMedia) : undefined,
          autoGenerated: false,
        }),
      });

      if (res.ok) {
        const newPost = await res.json();
        setPosts((prev) => [newPost, ...prev]);

        if (postStatus === "draft") {
          toast.success("Draft saved!");
        } else if (postStatus === "scheduled") {
          toast.success("Post scheduled!");
        }

        // Reset form
        setComposeContent("");
        setComposeScheduledAt("");
        setComposeMedia([]);
      } else {
        toast.error("Failed to save post");
      }
    } catch {
      toast.error("Failed to save post");
    }
  };

  const handlePublishNow = async () => {
    if (!composeContent.trim()) {
      toast.error("Please enter post content");
      return;
    }

    try {
      // First create the post
      const res = await fetch("/api/admin/social/posts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          content: composeContent,
          platform: composePlatform,
          status: "draft",
          category: composeCategory,
          mediaUrls: composeMedia.length > 0 ? JSON.stringify(composeMedia) : undefined,
        }),
      });

      if (res.ok) {
        const newPost = await res.json();
        // Then publish it
        const publishRes = await fetch(`/api/admin/social/posts/${newPost.id}/publish`, {
          method: "POST",
        });

        if (publishRes.ok) {
          const data = await publishRes.json();
          setPosts((prev) => [data.post, ...prev]);
          if (data.simulated) {
            toast.info("Post marked as published (simulated)", { description: "Connect social accounts with OAuth tokens to enable real publishing." });
          } else {
            toast.success("Post published successfully!");
          }
          setComposeContent("");
          setComposeScheduledAt("");
          setComposeMedia([]);
        } else {
          toast.error("Failed to publish post");
          setPosts((prev) => [newPost, ...prev]);
        }
      } else {
        toast.error("Failed to create post");
      }
    } catch {
      toast.error("Failed to publish post");
    }
  };

  const handlePublishExisting = async (postId: string) => {
    setPublishingId(postId);
    try {
      const res = await fetch(`/api/admin/social/posts/${postId}/publish`, {
        method: "POST",
      });
      if (res.ok) {
        const data = await res.json();
        setPosts((prev) => prev.map((p) => (p.id === postId ? data.post : p)));
        if (data.simulated) {
          toast.info("Post marked as published (simulated)", { description: "Connect social accounts with OAuth tokens to enable real publishing." });
        } else {
          toast.success("Post published successfully!");
        }
      } else {
        toast.error("Failed to publish post");
      }
    } catch {
      toast.error("Failed to publish post");
    } finally {
      setPublishingId(null);
    }
  };

  const handleDeletePost = async (postId: string) => {
    try {
      const res = await fetch(`/api/admin/social/posts/${postId}`, { method: "DELETE" });
      if (res.ok) {
        setPosts((prev) => prev.filter((p) => p.id !== postId));
        toast.success("Post deleted");
        setSelectedPost(null);
      } else {
        toast.error("Failed to delete post");
      }
    } catch {
      toast.error("Failed to delete post");
    }
  };

  const handleAddAccount = async () => {
    if (!accountForm.accountName || !accountForm.provider) {
      toast.error("Please fill in account name and provider");
      return;
    }
    setSavingAccount(true);
    try {
      const res = await fetch("/api/admin/social/accounts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(accountForm),
      });
      if (res.ok) {
        const newAccount = await res.json();
        setAccounts((prev) => [newAccount, ...prev]);
        toast.success("Account added!");
        setShowAccountDialog(false);
        setAccountForm({ provider: "linkedin", accountName: "", accountHandle: "", accessToken: "" });
      } else {
        const data = await res.json();
        toast.error(data.error || "Failed to add account");
      }
    } catch {
      toast.error("Failed to add account");
    } finally {
      setSavingAccount(false);
    }
  };

  const handleToggleAccount = async (accountId: string, currentActive: boolean) => {
    try {
      const res = await fetch(`/api/admin/social/accounts/${accountId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ isActive: !currentActive }),
      });
      if (res.ok) {
        const updated = await res.json();
        setAccounts((prev) => prev.map((a) => (a.id === accountId ? updated : a)));
        toast.success(updated.isActive ? "Account activated" : "Account deactivated");
      } else {
        toast.error("Failed to update account");
      }
    } catch {
      toast.error("Failed to update account");
    }
  };

  const handleDeleteAccount = async (accountId: string) => {
    try {
      const res = await fetch(`/api/admin/social/accounts/${accountId}`, { method: "DELETE" });
      if (res.ok) {
        setAccounts((prev) => prev.filter((a) => a.id !== accountId));
        toast.success("Account disconnected");
      } else {
        toast.error("Failed to disconnect account");
      }
    } catch {
      toast.error("Failed to disconnect account");
    }
  };

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (!files) return;

    Array.from(files).forEach((file) => {
      const reader = new FileReader();
      reader.onload = (ev) => {
        const result = ev.target?.result as string;
        if (result) {
          setComposeMedia((prev) => [...prev, result]);
        }
      };
      reader.readAsDataURL(file);
    });
  };

  // ─── Computed ──────────────────────────────────────────────────────

  const maxChars = PLATFORM_CONFIG[composePlatform]?.maxChars ?? 280;
  const charCount = composeContent.length;
  const isOverLimit = charCount > maxChars;
  const recentPosts = posts.slice(0, 5);

  // Calendar computed
  const monthStart = startOfMonth(calendarMonth);
  const monthEnd = endOfMonth(calendarMonth);
  const calStart = startOfWeek(monthStart, { weekStartsOn: 0 });
  const calEnd = endOfWeek(monthEnd, { weekStartsOn: 0 });
  const calendarDays = eachDayOfInterval({ start: calStart, end: calEnd });

  const postsByDate = posts.reduce<Record<string, SocialPost[]>>((acc, post) => {
    const dateKey = post.scheduledAt
      ? format(new Date(post.scheduledAt), "yyyy-MM-dd")
      : post.publishedAt
      ? format(new Date(post.publishedAt), "yyyy-MM-dd")
      : format(new Date(post.createdAt), "yyyy-MM-dd");
    if (!acc[dateKey]) acc[dateKey] = [];
    acc[dateKey].push(post);
    return acc;
  }, {});

  const selectedDayPosts = selectedDay ? postsByDate[format(selectedDay, "yyyy-MM-dd")] || [] : [];

  // Analytics computed
  const publishedPosts = posts.filter((p) => p.status === "published");
  const publishedByPlatform: Record<string, number> = {};
  publishedPosts.forEach((p) => {
    publishedByPlatform[p.platform] = (publishedByPlatform[p.platform] || 0) + 1;
  });

  // ─── Tab Config ────────────────────────────────────────────────────

  const tabs: { id: SocialTab; icon: React.ElementType; label: string }[] = [
    { id: "compose", icon: PenLine, label: "Compose" },
    { id: "calendar", icon: CalendarIcon, label: "Calendar" },
    { id: "accounts", icon: Users, label: "Accounts" },
    { id: "analytics", icon: BarChart3, label: "Analytics" },
  ];

  // ─── Render ────────────────────────────────────────────────────────

  return (
    <div className="min-h-screen flex flex-col bg-navy-900">
      <Navigation />

      <main className="flex-1">
        {/* Header */}
        <section className="border-b border-border/50 bg-navy-900/50">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-6">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
              className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"
            >
              <div>
                <div className="flex items-center gap-3 mb-1">
                  <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-eari-blue/10 border border-eari-blue/20">
                    <Share2 className="h-5 w-5 text-eari-blue" />
                  </div>
                  <h1 className="font-heading text-2xl sm:text-3xl font-bold text-foreground">
                    Social Media Hub
                  </h1>
                </div>
                <p className="text-muted-foreground font-sans text-sm ml-[52px]">
                  Schedule posts, auto-generate content, and manage social accounts
                </p>
              </div>
              <div className="flex items-center gap-3">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => { setLoading(true); Promise.all([fetchPosts(), fetchAccounts()]).finally(() => setLoading(false)); }}
                  disabled={loading}
                  className="border-border text-muted-foreground hover:text-foreground font-sans"
                >
                  <RefreshCw className={`h-4 w-4 mr-2 ${loading ? "animate-spin" : ""}`} />
                  Refresh
                </Button>
                <Link href="/admin">
                  <Button variant="ghost" size="sm" className="text-muted-foreground hover:text-foreground font-sans">
                    <ArrowLeft className="h-4 w-4 mr-2" />
                    Admin
                  </Button>
                </Link>
              </div>
            </motion.div>
          </div>
        </section>

        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-6">
          {/* Tab Navigation */}
          <div className="flex items-center gap-1 p-1.5 rounded-xl border border-border/40 bg-card/30 mb-6 overflow-x-auto">
            {tabs.map((tab) => {
              const Icon = tab.icon;
              return (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-lg transition-all duration-200 whitespace-nowrap ${
                    activeTab === tab.id
                      ? "bg-eari-blue/15 text-eari-blue-light border border-eari-blue/30"
                      : "text-muted-foreground hover:text-foreground hover:bg-navy-700/40 border border-transparent"
                  }`}
                >
                  <Icon className="h-4 w-4" />
                  {tab.label}
                </button>
              );
            })}
          </div>

          {/* ═══════════════════════════════════════════════════════════════
             COMPOSE TAB
             ═══════════════════════════════════════════════════════════════ */}
          {activeTab === "compose" && (
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
              {/* Simulation Notice */}
              <div className="lg:col-span-3">
                <div className="flex items-center gap-3 p-3 rounded-lg bg-amber-500/10 border border-amber-500/20">
                  <AlertTriangle className="h-4 w-4 text-amber-400 shrink-0" />
                  <p className="text-xs text-amber-400 font-sans">
                    <span className="font-semibold">Simulation Mode</span> — Publishing is currently simulated. Connect social accounts with OAuth tokens in the Accounts tab to enable real posting to LinkedIn, Twitter/X, and Facebook.
                  </p>
                </div>
              </div>
              {/* Main Compose Area */}
              <div className="lg:col-span-2 space-y-4">
                {/* Platform Selector */}
                <Card className="bg-navy-800 border-border/50">
                  <CardHeader className="pb-3">
                    <CardTitle className="text-sm font-medium text-foreground flex items-center gap-2">
                      <Share2 className="h-4 w-4" />
                      Platform
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="flex flex-wrap gap-2">
                      {Object.entries(PLATFORM_CONFIG).map(([key, config]) => (
                        <button
                          key={key}
                          onClick={() => setComposePlatform(key)}
                          className={`flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium transition-all border ${
                            composePlatform === key
                              ? "border-2 shadow-sm"
                              : "border-border/50 bg-navy-700 text-muted-foreground hover:bg-navy-700/60"
                          }`}
                          style={composePlatform === key ? { borderColor: config.color, backgroundColor: `${config.color}10`, color: config.color } : {}}
                        >
                          <PlatformIcon platform={key} size={18} />
                          {config.name}
                        </button>
                      ))}
                    </div>
                  </CardContent>
                </Card>

                {/* Content Editor */}
                <Card className="bg-navy-800 border-border/50">
                  <CardHeader className="pb-3">
                    <div className="flex items-center justify-between">
                      <CardTitle className="text-sm font-medium text-foreground flex items-center gap-2">
                        <PenLine className="h-4 w-4" />
                        Content
                      </CardTitle>
                      <div className="flex items-center gap-2">
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={handleGenerate}
                          disabled={generating}
                          className="text-xs border-eari-blue/30 text-eari-blue-light hover:bg-eari-blue/15"
                        >
                          <Sparkles className={`h-3.5 w-3.5 mr-1 ${generating ? "animate-spin" : ""}`} />
                          Auto-Generate
                        </Button>
                        <span className={`text-xs font-mono ${isOverLimit ? "text-red-500 font-bold" : charCount > maxChars * 0.9 ? "text-amber-400" : "text-muted-foreground/70"}`}>
                          {charCount}/{maxChars}
                        </span>
                      </div>
                    </div>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    {/* Category selector */}
                    <div className="flex items-center gap-2">
                      <span className="text-xs font-medium text-muted-foreground">Category:</span>
                      <div className="flex gap-1">
                        {["custom", "benchmark", "compliance", "certification", "promotion"].map((cat) => (
                          <button
                            key={cat}
                            onClick={() => setComposeCategory(cat)}
                            className={`px-3 py-1 rounded-full text-xs font-medium transition-all capitalize ${
                              composeCategory === cat
                                ? "bg-emerald-500/15 text-emerald-400 border border-emerald-500/30"
                                : "bg-navy-700/50 text-muted-foreground border border-border/50 hover:bg-navy-700/60"
                            }`}
                          >
                            {cat}
                          </button>
                        ))}
                      </div>
                    </div>

                    <textarea
                      value={composeContent}
                      onChange={(e) => setComposeContent(e.target.value)}
                      placeholder="Write your social media post here..."
                      className="w-full min-h-[200px] p-4 rounded-lg border border-border/60 bg-navy-700 text-sm text-foreground placeholder:text-muted-foreground/70 focus:outline-none focus:ring-2 focus:ring-eari-blue/30 focus:border-eari-blue/50 resize-y font-sans"
                    />

                    {/* Image upload */}
                    <div className="space-y-2">
                      <label className="flex items-center gap-2 cursor-pointer">
                        <div className="flex items-center gap-2 px-3 py-2 rounded-lg border border-dashed border-border/50 text-muted-foreground hover:border-eari-blue/50 hover:text-eari-blue-light transition-colors text-xs">
                          <ImagePlus className="h-4 w-4" />
                          Add Images
                        </div>
                        <input
                          type="file"
                          accept="image/*"
                          multiple
                          className="hidden"
                          onChange={handleImageUpload}
                        />
                      </label>
                      {composeMedia.length > 0 && (
                        <div className="flex flex-wrap gap-2">
                          {composeMedia.map((url, idx) => (
                            <div key={idx} className="relative group">
                              <img src={url} alt="" className="w-16 h-16 rounded-lg object-cover border border-border/50" />
                              <button
                                onClick={() => setComposeMedia((prev) => prev.filter((_, i) => i !== idx))}
                                className="absolute -top-1 -right-1 w-5 h-5 rounded-full bg-red-500 text-white flex items-center justify-center text-[10px] opacity-0 group-hover:opacity-100 transition-opacity"
                              >
                                ×
                              </button>
                            </div>
                          ))}
                        </div>
                      )}
                    </div>

                    {/* Schedule */}
                    <div className="flex items-center gap-3">
                      <label className="text-xs font-medium text-muted-foreground font-sans">Schedule:</label>
                      <input
                        type="datetime-local"
                        value={composeScheduledAt}
                        onChange={(e) => setComposeScheduledAt(e.target.value)}
                        className="px-3 py-1.5 rounded-lg border border-border/60 bg-navy-700 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-eari-blue/30 focus:border-eari-blue/50 font-sans"
                      />
                    </div>

                    {/* Action Buttons */}
                    <div className="flex items-center gap-3 pt-2">
                      <Button
                        variant="outline"
                        onClick={() => handleSavePost("draft")}
                        className="border-border/50 text-muted-foreground hover:bg-navy-700/60"
                      >
                        <FileEdit className="h-4 w-4 mr-2" />
                        Save Draft
                      </Button>
                      {composeScheduledAt && (
                        <Button
                          variant="outline"
                          onClick={() => handleSavePost("scheduled")}
                          className="border-amber-500/30 text-amber-400 hover:bg-amber-500/15"
                        >
                          <Clock className="h-4 w-4 mr-2" />
                          Schedule
                        </Button>
                      )}
                      <Button
                        onClick={handlePublishNow}
                        className="bg-eari-blue hover:bg-eari-blue-dark text-white"
                      >
                        <Send className="h-4 w-4 mr-2" />
                        Publish Now
                      </Button>
                    </div>
                  </CardContent>
                </Card>

                {/* Preview */}
                {composeContent && (
                  <Card className="bg-navy-800 border-border/50">
                    <CardHeader className="pb-3">
                      <CardTitle className="text-sm font-medium text-foreground">Preview</CardTitle>
                    </CardHeader>
                    <CardContent>
                      <div className="rounded-lg border border-border/20 p-4 bg-navy-700/50 max-w-md">
                        <div className="flex items-center gap-2 mb-3">
                          <PlatformIcon platform={composePlatform} size={20} />
                          <span className="text-sm font-medium text-foreground">
                            {PLATFORM_CONFIG[composePlatform]?.name ?? "Post"}
                          </span>
                        </div>
                        <p className="text-sm text-foreground whitespace-pre-wrap">{composeContent}</p>
                        {composeMedia.length > 0 && (
                          <div className="flex flex-wrap gap-2 mt-3">
                            {composeMedia.map((url, idx) => (
                              <img key={idx} src={url} alt="" className="w-24 h-24 rounded-lg object-cover border border-border/50" />
                            ))}
                          </div>
                        )}
                      </div>
                    </CardContent>
                  </Card>
                )}
              </div>

              {/* Recent Posts Sidebar */}
              <div className="space-y-4">
                <Card className="bg-navy-800 border-border/50">
                  <CardHeader className="pb-3">
                    <CardTitle className="text-sm font-medium text-foreground">Recent Posts</CardTitle>
                  </CardHeader>
                  <CardContent>
                    {loading ? (
                      <div className="space-y-3">
                        {[1, 2, 3].map((i) => (
                          <div key={i} className="h-16 animate-pulse rounded-lg bg-navy-700" />
                        ))}
                      </div>
                    ) : recentPosts.length === 0 ? (
                      <p className="text-sm text-muted-foreground/70 text-center py-6">No posts yet</p>
                    ) : (
                      <div className="space-y-3 max-h-96 overflow-y-auto">
                        {recentPosts.map((post) => (
                          <div
                            key={post.id}
                            onClick={() => setSelectedPost(post)}
                            className="flex items-start gap-3 p-3 rounded-lg border border-border/20 hover:border-border/50 hover:bg-navy-700/60 cursor-pointer transition-all"
                          >
                            <PlatformIcon platform={post.platform} size={18} />
                            <div className="flex-1 min-w-0">
                              <p className="text-xs text-foreground truncate">{post.content}</p>
                              <div className="flex items-center gap-2 mt-1">
                                {postStatusBadge(post.status)}
                                {post.autoGenerated && (
                                  <Badge className="bg-purple-500/15 text-purple-400 border-purple-500/30 text-[10px]">
                                    <Sparkles className="h-2.5 w-2.5 mr-0.5" />
                                    AI
                                  </Badge>
                                )}
                              </div>
                            </div>
                          </div>
                        ))}
                      </div>
                    )}
                  </CardContent>
                </Card>

                {/* Quick Stats */}
                <Card className="bg-navy-800 border-border/50">
                  <CardHeader className="pb-3">
                    <CardTitle className="text-sm font-medium text-foreground">Quick Stats</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-3">
                      <div className="flex items-center justify-between">
                        <span className="text-xs text-muted-foreground">Total Posts</span>
                        <span className="text-sm font-bold text-foreground font-mono">{posts.length}</span>
                      </div>
                      <div className="flex items-center justify-between">
                        <span className="text-xs text-muted-foreground">Scheduled</span>
                        <span className="text-sm font-bold text-amber-400 font-mono">{posts.filter((p) => p.status === "scheduled").length}</span>
                      </div>
                      <div className="flex items-center justify-between">
                        <span className="text-xs text-muted-foreground">Published</span>
                        <span className="text-sm font-bold text-emerald-400 font-mono">{publishedPosts.length}</span>
                      </div>
                      <div className="flex items-center justify-between">
                        <span className="text-xs text-muted-foreground">Connected Accounts</span>
                        <span className="text-sm font-bold text-foreground font-mono">{accounts.filter((a) => a.isActive).length}</span>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </div>
          )}

          {/* ═══════════════════════════════════════════════════════════════
             CALENDAR TAB
             ═══════════════════════════════════════════════════════════════ */}
          {activeTab === "calendar" && (
            <div className="space-y-6">
              {/* Calendar Navigation */}
              <div className="flex items-center justify-between">
                <h2 className="text-lg font-bold text-foreground font-heading">
                  {format(calendarMonth, "MMMM yyyy")}
                </h2>
                <div className="flex items-center gap-2">
                  <Button variant="outline" size="sm" onClick={() => setCalendarMonth(subMonths(calendarMonth, 1))}>
                    <ChevronLeft className="h-4 w-4" />
                  </Button>
                  <Button variant="outline" size="sm" onClick={() => setCalendarMonth(new Date())}>
                    Today
                  </Button>
                  <Button variant="outline" size="sm" onClick={() => setCalendarMonth(addMonths(calendarMonth, 1))}>
                    <ChevronRight className="h-4 w-4" />
                  </Button>
                </div>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
                {/* Calendar Grid */}
                <div className="lg:col-span-3">
                  <Card className="bg-navy-800 border-border/50 overflow-hidden">
                    {/* Day headers */}
                    <div className="grid grid-cols-7 border-b border-border/20">
                      {["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day) => (
                        <div key={day} className="px-2 py-3 text-center text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                          {day}
                        </div>
                      ))}
                    </div>

                    {/* Calendar cells */}
                    <div className="grid grid-cols-7">
                      {calendarDays.map((day) => {
                        const dateKey = format(day, "yyyy-MM-dd");
                        const dayPosts = postsByDate[dateKey] || [];
                        const isCurrentMonth = isSameMonth(day, calendarMonth);
                        const isSelected = selectedDay && isSameDay(day, selectedDay);
                        const isTodayDate = isToday(day);

                        return (
                          <div
                            key={dateKey}
                            onClick={() => setSelectedDay(day)}
                            className={`min-h-[80px] sm:min-h-[100px] p-1.5 border-b border-r border-border/20 cursor-pointer transition-colors ${
                              !isCurrentMonth ? "bg-navy-900/50" : "bg-navy-800 hover:bg-navy-700/60"
                            } ${isSelected ? "ring-2 ring-eari-blue-light ring-inset" : ""}`}
                          >
                            <div className="flex items-center justify-between mb-1">
                              <span className={`text-xs font-medium ${
                                !isCurrentMonth ? "text-muted-foreground/50" :
                                isTodayDate ? "bg-eari-blue text-white rounded-full w-6 h-6 flex items-center justify-center" :
                                "text-muted-foreground"
                              }`}>
                                {format(day, "d")}
                              </span>
                              {isCurrentMonth && dayPosts.length === 0 && (
                                <button
                                  onClick={(e) => {
                                    e.stopPropagation();
                                    setSelectedDay(day);
                                    setActiveTab("compose");
                                  }}
                                  className="opacity-0 group-hover:opacity-100 text-muted-foreground/70 hover:text-eari-blue-light transition-opacity"
                                >
                                  <Plus className="h-3.5 w-3.5" />
                                </button>
                              )}
                            </div>
                            <div className="space-y-0.5">
                              {dayPosts.slice(0, 3).map((post) => (
                                <div
                                  key={post.id}
                                  className="flex items-center gap-1 px-1 py-0.5 rounded text-[10px] truncate"
                                  style={{
                                    backgroundColor: `${PLATFORM_CONFIG[post.platform]?.color || "#64748b"}15`,
                                    color: PLATFORM_CONFIG[post.platform]?.color || "#64748b",
                                  }}
                                >
                                  <PlatformIcon platform={post.platform} size={10} />
                                  <span className="truncate">{post.content.slice(0, 20)}</span>
                                </div>
                              ))}
                              {dayPosts.length > 3 && (
                                <p className="text-[10px] text-muted-foreground/70 pl-1">+{dayPosts.length - 3} more</p>
                              )}
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </Card>
                </div>

                {/* Selected Day Posts */}
                <div className="space-y-4">
                  <Card className="bg-navy-800 border-border/50">
                    <CardHeader className="pb-3">
                      <CardTitle className="text-sm font-medium text-foreground">
                        {selectedDay ? format(selectedDay, "EEEE, MMMM d") : "Select a day"}
                      </CardTitle>
                    </CardHeader>
                    <CardContent>
                      {!selectedDay ? (
                        <p className="text-sm text-muted-foreground/70 text-center py-4">Click a day on the calendar</p>
                      ) : selectedDayPosts.length === 0 ? (
                        <div className="text-center py-4">
                          <p className="text-sm text-muted-foreground/70 mb-3">No posts for this day</p>
                          <Button
                            size="sm"
                            onClick={() => { setActiveTab("compose"); }}
                            className="bg-eari-blue hover:bg-eari-blue-dark text-white text-xs"
                          >
                            <Plus className="h-3.5 w-3.5 mr-1" />
                            Create Post
                          </Button>
                        </div>
                      ) : (
                        <div className="space-y-3 max-h-96 overflow-y-auto">
                          {selectedDayPosts.map((post) => (
                            <div
                              key={post.id}
                              onClick={() => setSelectedPost(post)}
                              className="p-3 rounded-lg border border-border/20 hover:border-border/50 cursor-pointer transition-all"
                            >
                              <div className="flex items-center gap-2 mb-1">
                                <PlatformIcon platform={post.platform} size={16} />
                                {postStatusBadge(post.status)}
                              </div>
                              <p className="text-xs text-foreground line-clamp-3">{post.content}</p>
                              {post.scheduledAt && (
                                <p className="text-[10px] text-muted-foreground/70 mt-1">
                                  <Clock className="h-3 w-3 inline mr-1" />
                                  {format(new Date(post.scheduledAt), "h:mm a")}
                                </p>
                              )}
                            </div>
                          ))}
                        </div>
                      )}
                    </CardContent>
                  </Card>

                  {/* Platform Legend */}
                  <Card className="bg-navy-800 border-border/50">
                    <CardContent className="p-4">
                      <p className="text-xs font-medium text-muted-foreground mb-2">Platform Colors</p>
                      <div className="space-y-1.5">
                        {Object.entries(PLATFORM_CONFIG).map(([key, config]) => (
                          <div key={key} className="flex items-center gap-2">
                            <div className="w-3 h-3 rounded-full" style={{ backgroundColor: config.color }} />
                            <span className="text-xs text-muted-foreground">{config.name}</span>
                          </div>
                        ))}
                      </div>
                    </CardContent>
                  </Card>
                </div>
              </div>
            </div>
          )}

          {/* ═══════════════════════════════════════════════════════════════
             ACCOUNTS TAB
             ═══════════════════════════════════════════════════════════════ */}
          {activeTab === "accounts" && (
            <div className="space-y-6">
              <div className="flex items-center justify-between">
                <div>
                  <h2 className="text-lg font-bold text-foreground font-heading">Connected Accounts</h2>
                  <p className="text-sm text-muted-foreground">Manage your social media connections</p>
                </div>
                <Button
                  onClick={() => setShowAccountDialog(true)}
                  className="bg-eari-blue hover:bg-eari-blue-dark text-white"
                >
                  <Plus className="h-4 w-4 mr-2" />
                  Add Account
                </Button>
              </div>

              {loading ? (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  {[1, 2, 3].map((i) => (
                    <div key={i} className="h-48 animate-pulse rounded-xl bg-navy-700" />
                  ))}
                </div>
              ) : accounts.length === 0 ? (
                <Card className="bg-navy-800 border-border/50">
                  <CardContent className="p-12 text-center">
                    <Users className="h-12 w-12 text-muted-foreground/50 mx-auto mb-4" />
                    <h3 className="text-lg font-semibold text-foreground mb-2">No accounts connected</h3>
                    <p className="text-sm text-muted-foreground/70 mb-4">Add your first social media account to get started</p>
                    <Button
                      onClick={() => setShowAccountDialog(true)}
                      className="bg-eari-blue hover:bg-eari-blue-dark text-white"
                    >
                      <Plus className="h-4 w-4 mr-2" />
                      Add Account
                    </Button>
                  </CardContent>
                </Card>
              ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  {accounts.map((account) => {
                    const config = PLATFORM_CONFIG[account.provider];
                    return (
                      <motion.div
                        key={account.id}
                        initial={{ opacity: 0, y: 12 }}
                        animate={{ opacity: 1, y: 0 }}
                      >
                        <Card className="bg-navy-800 border-border/50 hover:border-border transition-colors">
                          <CardContent className="p-6">
                            <div className="flex items-start justify-between mb-4">
                              <div className="flex items-center gap-3">
                                <div
                                  className="w-10 h-10 rounded-lg flex items-center justify-center"
                                  style={{ backgroundColor: `${config?.color || "#64748b"}15` }}
                                >
                                  <PlatformIcon platform={account.provider} size={22} />
                                </div>
                                <div>
                                  <p className="text-sm font-semibold text-foreground">{account.accountName}</p>
                                  {account.accountHandle && (
                                    <p className="text-xs text-muted-foreground">{account.accountHandle}</p>
                                  )}
                                </div>
                              </div>
                              <Badge className={account.isActive ? "bg-emerald-500/15 text-emerald-400 border-emerald-500/30 text-[10px]" : "bg-navy-700 text-muted-foreground border-border/50 text-[10px]"}>
                                {account.isActive ? "Active" : "Inactive"}
                              </Badge>
                            </div>

                            <div className="space-y-2 mb-4">
                              <div className="flex items-center justify-between">
                                <span className="text-xs text-muted-foreground">Provider</span>
                                <span className="text-xs font-medium text-foreground capitalize">{account.provider}</span>
                              </div>
                              <div className="flex items-center justify-between">
                                <span className="text-xs text-muted-foreground">Last Sync</span>
                                <span className="text-xs text-foreground">{account.lastSyncAt ? formatDate(account.lastSyncAt) : "Never"}</span>
                              </div>
                              <div className="flex items-center justify-between">
                                <span className="text-xs text-muted-foreground">Token</span>
                                <span className="text-xs text-foreground">{account.accessToken ? "••••••••" : "Not set"}</span>
                              </div>
                            </div>

                            <div className="flex items-center gap-2">
                              <Button
                                variant="outline"
                                size="sm"
                                onClick={() => handleToggleAccount(account.id, account.isActive)}
                                className={`flex-1 text-xs ${account.isActive ? "border-amber-500/30 text-amber-400 hover:bg-amber-500/15" : "border-emerald-500/30 text-emerald-400 hover:bg-emerald-500/15"}`}
                              >
                                {account.isActive ? "Deactivate" : "Activate"}
                              </Button>
                              <Button
                                variant="outline"
                                size="sm"
                                onClick={() => handleDeleteAccount(account.id)}
                                className="text-xs border-red-500/30 text-red-400 hover:bg-red-500/15"
                              >
                                <Unplug className="h-3.5 w-3.5 mr-1" />
                                Disconnect
                              </Button>
                            </div>
                          </CardContent>
                        </Card>
                      </motion.div>
                    );
                  })}
                </div>
              )}
            </div>
          )}

          {/* ═══════════════════════════════════════════════════════════════
             ANALYTICS TAB
             ═══════════════════════════════════════════════════════════════ */}
          {activeTab === "analytics" && (
            <div className="space-y-6">
              {/* Stats Summary */}
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                <Card className="bg-navy-800 border-border/50">
                  <CardContent className="p-6">
                    <div className="flex items-center gap-3 mb-2">
                      <div className="w-8 h-8 rounded-md bg-emerald-500/15 flex items-center justify-center">
                        <CheckCircle2 className="h-4 w-4 text-emerald-400" />
                      </div>
                      <span className="text-sm text-muted-foreground">Published</span>
                    </div>
                    <p className="text-3xl font-bold text-foreground font-mono">{publishedPosts.length}</p>
                  </CardContent>
                </Card>
                <Card className="bg-navy-800 border-border/50">
                  <CardContent className="p-6">
                    <div className="flex items-center gap-3 mb-2">
                      <div className="w-8 h-8 rounded-md bg-amber-500/15 flex items-center justify-center">
                        <Clock className="h-4 w-4 text-amber-400" />
                      </div>
                      <span className="text-sm text-muted-foreground">Scheduled</span>
                    </div>
                    <p className="text-3xl font-bold text-foreground font-mono">{posts.filter((p) => p.status === "scheduled").length}</p>
                  </CardContent>
                </Card>
                <Card className="bg-navy-800 border-border/50">
                  <CardContent className="p-6">
                    <div className="flex items-center gap-3 mb-2">
                      <div className="w-8 h-8 rounded-md bg-navy-700 flex items-center justify-center">
                        <FileEdit className="h-4 w-4 text-muted-foreground" />
                      </div>
                      <span className="text-sm text-muted-foreground">Drafts</span>
                    </div>
                    <p className="text-3xl font-bold text-foreground font-mono">{posts.filter((p) => p.status === "draft").length}</p>
                  </CardContent>
                </Card>
                <Card className="bg-navy-800 border-border/50">
                  <CardContent className="p-6">
                    <div className="flex items-center gap-3 mb-2">
                      <div className="w-8 h-8 rounded-md bg-red-500/15 flex items-center justify-center">
                        <XCircle className="h-4 w-4 text-red-400" />
                      </div>
                      <span className="text-sm text-muted-foreground">Failed</span>
                    </div>
                    <p className="text-3xl font-bold text-foreground font-mono">{posts.filter((p) => p.status === "failed").length}</p>
                  </CardContent>
                </Card>
              </div>

              {/* Published by Platform */}
              <Card className="bg-navy-800 border-border/50">
                <CardHeader>
                  <CardTitle className="text-sm font-medium text-foreground">Published by Platform</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    {Object.entries(PLATFORM_CONFIG).filter(([key]) => key !== "all").map(([key, config]) => {
                      const count = publishedByPlatform[key] || 0;
                      const total = publishedPosts.length || 1;
                      const pct = Math.round((count / total) * 100);
                      return (
                        <div key={key}>
                          <div className="flex items-center justify-between mb-1">
                            <div className="flex items-center gap-2">
                              <PlatformIcon platform={key} size={16} />
                              <span className="text-sm font-medium text-foreground">{config.name}</span>
                            </div>
                            <span className="text-sm text-muted-foreground">{count} posts</span>
                          </div>
                          <div className="w-full bg-navy-700 rounded-full h-2">
                            <div
                              className="h-2 rounded-full transition-all duration-500"
                              style={{ width: `${pct}%`, backgroundColor: config.color }}
                            />
                          </div>
                        </div>
                      );
                    })}
                    {publishedPosts.length === 0 && (
                      <p className="text-sm text-muted-foreground/70 text-center py-4">No published posts yet</p>
                    )}
                  </div>
                </CardContent>
              </Card>

              {/* Analytics Coming Soon */}
              <Card className="bg-navy-800 border-border/50">
                <CardContent className="p-12 text-center">
                  <BarChart3 className="h-16 w-16 text-muted-foreground/30 mx-auto mb-4" />
                  <h3 className="text-lg font-semibold text-foreground mb-2">Full Analytics Coming Soon</h3>
                  <p className="text-sm text-muted-foreground/70 max-w-md mx-auto">
                    Track engagement, reach, and conversion from social posts to assessment signups.
                    Detailed analytics will be available once social API integrations are complete.
                  </p>
                </CardContent>
              </Card>
            </div>
          )}
        </div>
      </main>

      <Footer />

      {/* ─── Add Account Dialog ────────────────────────────────────────── */}
      <Dialog open={showAccountDialog} onOpenChange={setShowAccountDialog}>
        <DialogContent className="bg-navy-800 border-border/60 text-foreground sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-foreground">
              <Plus className="h-5 w-5 text-eari-blue" />
              Add Social Account
            </DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div>
              <label className="text-sm font-medium text-muted-foreground font-sans mb-1.5 block">Platform</label>
              <Select value={accountForm.provider} onValueChange={(v) => setAccountForm((prev) => ({ ...prev, provider: v }))}>
                <SelectTrigger className="w-full bg-navy-700 border-border/60 text-foreground font-sans">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent className="bg-navy-800 border-border/60">
                  <SelectItem value="linkedin">LinkedIn</SelectItem>
                  <SelectItem value="twitter">Twitter/X</SelectItem>
                  <SelectItem value="facebook">Facebook</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div>
              <label className="text-sm font-medium text-muted-foreground font-sans mb-1.5 block">Account Name</label>
              <Input
                value={accountForm.accountName}
                onChange={(e) => setAccountForm((prev) => ({ ...prev, accountName: e.target.value }))}
                placeholder="e.g., E-ARI Official"
                className="bg-navy-700 border-border/60 text-foreground font-sans"
              />
            </div>
            <div>
              <label className="text-sm font-medium text-muted-foreground font-sans mb-1.5 block">Handle</label>
              <Input
                value={accountForm.accountHandle}
                onChange={(e) => setAccountForm((prev) => ({ ...prev, accountHandle: e.target.value }))}
                placeholder="@eari_official"
                className="bg-navy-700 border-border/60 text-foreground font-sans"
              />
            </div>
            <div>
              <label className="text-sm font-medium text-muted-foreground font-sans mb-1.5 block">Access Token</label>
              <Input
                type="password"
                value={accountForm.accessToken}
                onChange={(e) => setAccountForm((prev) => ({ ...prev, accessToken: e.target.value }))}
                placeholder="Paste your OAuth access token"
                className="bg-navy-700 border-border/60 text-foreground font-sans"
              />
              <p className="text-[10px] text-muted-foreground/70 mt-1">Manual token entry for now — real OAuth flow coming soon</p>
            </div>
            <div className="flex items-center justify-end gap-3 pt-2">
              <Button variant="outline" onClick={() => setShowAccountDialog(false)} className="border-border/50 text-muted-foreground hover:text-foreground">
                Cancel
              </Button>
              <Button
                onClick={handleAddAccount}
                disabled={savingAccount}
                className="bg-eari-blue hover:bg-eari-blue-dark text-white"
              >
                {savingAccount ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : <Plus className="h-4 w-4 mr-2" />}
                Add Account
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>

      {/* ─── Post Detail Dialog ────────────────────────────────────────── */}
      <Dialog open={!!selectedPost} onOpenChange={(open) => { if (!open) setSelectedPost(null); }}>
        <DialogContent className="bg-navy-800 border-border/60 text-foreground sm:max-w-lg">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-foreground">
              <PlatformIcon platform={selectedPost?.platform ?? "all"} size={20} />
              Post Details
            </DialogTitle>
          </DialogHeader>
          {selectedPost && (
            <div className="space-y-4 py-4">
              <div className="flex items-center gap-2">
                {postStatusBadge(selectedPost.status)}
                {selectedPost.autoGenerated && (
                  <Badge className="bg-purple-500/15 text-purple-400 border-purple-500/30 text-xs">
                    <Sparkles className="h-3 w-3 mr-1" />
                    AI Generated
                  </Badge>
                )}
                {selectedPost.category && (
                  <Badge className="bg-navy-700 text-muted-foreground border-border/50 text-xs capitalize">
                    {selectedPost.category}
                  </Badge>
                )}
              </div>

              <p className="text-sm text-foreground whitespace-pre-wrap bg-navy-700/50 p-4 rounded-lg border border-border/50">
                {selectedPost.content}
              </p>

              <div className="grid grid-cols-2 gap-3 text-sm">
                <div>
                  <span className="text-muted-foreground">Platform</span>
                  <p className="font-medium text-foreground capitalize">{selectedPost.platform}</p>
                </div>
                <div>
                  <span className="text-muted-foreground">Created</span>
                  <p className="font-medium text-foreground">{formatDate(selectedPost.createdAt)}</p>
                </div>
                {selectedPost.scheduledAt && (
                  <div>
                    <span className="text-muted-foreground">Scheduled</span>
                    <p className="font-medium text-amber-400">{formatDate(selectedPost.scheduledAt)}</p>
                  </div>
                )}
                {selectedPost.publishedAt && (
                  <div>
                    <span className="text-muted-foreground">Published</span>
                    <p className="font-medium text-emerald-400">{formatDate(selectedPost.publishedAt)}</p>
                  </div>
                )}
                {selectedPost.failedReason && (
                  <div className="col-span-2">
                    <span className="text-muted-foreground">Failed Reason</span>
                    <p className="font-medium text-red-400">{selectedPost.failedReason}</p>
                  </div>
                )}
              </div>

              <div className="flex items-center gap-2 pt-2">
                {(selectedPost.status === "draft" || selectedPost.status === "scheduled" || selectedPost.status === "failed") && (
                  <Button
                    onClick={() => handlePublishExisting(selectedPost.id)}
                    disabled={publishingId === selectedPost.id}
                    className="bg-eari-blue hover:bg-eari-blue-dark text-white"
                  >
                    {publishingId === selectedPost.id ? (
                      <Loader2 className="h-4 w-4 animate-spin mr-2" />
                    ) : (
                      <Send className="h-4 w-4 mr-2" />
                    )}
                    Publish Now
                  </Button>
                )}
                <Button
                  variant="outline"
                  onClick={() => handleDeletePost(selectedPost.id)}
                  className="border-red-500/30 text-red-400 hover:bg-red-500/15"
                >
                  <Trash2 className="h-4 w-4 mr-2" />
                  Delete
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
